# Generated by Django 5.1.3 on 2024-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
