# Generated by Django 5.1.3 on 2025-01-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0004_alter_expense_date_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
